# Generated by Django 6.0.3 on 2026-03-30 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='established_year',
            field=models.CharField(default='2079', help_text='Year of establishment (e.g., 2079 BS)', max_length=10),
        ),
    ]
