# Generated by Django 6.0.3 on 2026-03-30 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_sitesettings_established_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='member_count',
            field=models.CharField(default='5000+', help_text='Number of members (e.g., 5000+)', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='service_center_count',
            field=models.PositiveIntegerField(default=3, help_text='Number of service centers/branch offices'),
        ),
    ]
