# Generated by Django 6.0.3 on 2026-03-30 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_sitesettings_member_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='about_cooperative_image',
            field=models.ImageField(blank=True, help_text='About section image (replaces about-cooperative.svg)', null=True, upload_to='home/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='empowerment_1_image',
            field=models.ImageField(blank=True, help_text='Women empowerment image 1 (replaces empowerment-1.svg)', null=True, upload_to='home/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='empowerment_2_image',
            field=models.ImageField(blank=True, help_text='Women empowerment image 2 (replaces empowerment-2.svg)', null=True, upload_to='home/'),
        ),
        migrations.AddField(
            model_name='vmgo',
            name='goals_image',
            field=models.ImageField(blank=True, help_text='Replaces goals.svg', null=True, upload_to='vmgo/', verbose_name='Goals Image'),
        ),
        migrations.AddField(
            model_name='vmgo',
            name='mission_image',
            field=models.ImageField(blank=True, help_text='Replaces mission.svg', null=True, upload_to='vmgo/', verbose_name='Mission Image'),
        ),
        migrations.AddField(
            model_name='vmgo',
            name='objectives_image',
            field=models.ImageField(blank=True, help_text='Replaces objectives.svg', null=True, upload_to='vmgo/', verbose_name='Objectives Image'),
        ),
        migrations.AddField(
            model_name='vmgo',
            name='vision_image',
            field=models.ImageField(blank=True, help_text='Replaces vision.svg', null=True, upload_to='vmgo/', verbose_name='Vision Image'),
        ),
    ]
